Data_Samples = 25000;
Training_Set_Rate = 0.995;
ValidationFrequency = 300;
SNR = 0:5:20;

[XTrain_RSRP, YTrain_RSRP, XValidation_RSRP, YValidation_RSRP] = Data_Generation_ReEsNet_48_CommuRayleigh(Training_Set_Rate, SNR, Data_Samples);

Input_Layer_Size = size(XTrain_RSRP, [1, 2, 3]);

SL102
%Improved_ReEsNet
%Improved_Neural_Network
%ReEsNet

% Option settings
Options = trainingOptions('adam', ...
    'MaxEpochs',100, ...
    'MiniBatchSize',128, ...
    'InitialLearnRate',1e-3, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.5, ...
    'LearnRateDropPeriod',20, ...
    'ValidationData',{XValidation_RSRP,YValidation_RSRP}, ...
    'ValidationFrequency',ValidationFrequency, ...
    'Shuffle','every-epoch', ...
    'Verbose',1, ...
    'L2Regularization',0.0000000001, ...
    'ExecutionEnvironment','auto', ...%'parallel'
    'Plots','training-progress');

% Train Network
[DNN_Trained, info] = trainNetwork(XTrain_RSRP, YTrain_RSRP, lgraph_1, Options);

% Network Pruning
%CDF_Layerweights
